pom.xml, src/main/java/dev/realtards/wzsnacknbites/WzSnackNBitesApiApplication.java, src/main/java/dev/realtards/wzsnacknbites/configurations/ApplicationProperties.java, src/main/java/dev/realtards/wzsnacknbites/controllers/IndexController.java, src/main/java/dev/realtards/wzsnacknbites/utils/UptimeTracker.java, src/main/resources/application.properties, src/main/resources/templates/status.html
- Created templated Thymeleaf page that can be injected by the controller.
- Added ApplicationProperties class to read from application.properties
- Custom version and repositoryUrl property
=> Add status page for the API

.env.example, .gitignore, pom.xml, src/main/java/dev/realtards/wzsnacknbites/boostrappers/DatabaseBootstrapper.java, src/main/java/dev/realtards/wzsnacknbites/configurations/ApplicationProperties.java, src/main/java/dev/realtards/wzsnacknbites/configurations/DatabaseConfiguration.java, src/main/java/dev/realtards/wzsnacknbites/configurations/DeveloperConfiguration.java, src/main/java/dev/realtards/wzsnacknbites/configurations/DotenvConfiguration.java, src/main/java/dev/realtards/wzsnacknbites/services/AccountServiceImpl.java, src/main/resources/application-postgres.properties, src/main/resources/application.properties
Added `dotenv` configuration and application profile for database. Where it defaults to H2 if `postgres` profile is not being run along with `spring-boot:run`.
To run with postgres, do:
```shell
mvn spring-boot:run -Dspring-boot.run.profiles=postgres
```
=> Initialize postgres profile and connection

src/main/java/dev/realtards/wzsnacknbites/dtos/account/AccountPatchDto.java, src/main/java/dev/realtards/wzsnacknbites/dtos/account/AccountPutDto.java, src/main/java/dev/realtards/wzsnacknbites/services/AccountServiceImpl.java
=> Remove privilege field for account put (update) dto

src/main/java/dev/realtards/kuenyawz/advice/ErrorHandler.java, src/main/java/dev/realtards/kuenyawz/responses/ListedErrors.java
This improves readability of errors caused by validation checks
=> Refactor methodargumentnotvalidexception handler with mapped errors

src/main/java/dev/realtards/kuenyawz/utils/idgenerator/SnowFlakeIdGenerator.java
=> feat: allow other methods to inject snowflake generator and use it

src/main/java/dev/realtards/kuenyawz/services/AccountServiceImpl.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java, src/main/java/dev/realtards/kuenyawz/services/VariantServiceImpl.java
=> Remove unnecessary log.info on service classes

src/main/java/dev/realtards/kuenyawz/controllers/ProductImageController.java, src/main/java/dev/realtards/kuenyawz/controllers/SimulatorController.java
=> refactor: simulator to its own controller

pom.xml, src/main/java/dev/realtards/kuenyawz/advice/GlobalExceptionHandler.java, src/main/java/dev/realtards/kuenyawz/configurations/AopConfiguration.java, src/main/java/dev/realtards/kuenyawz/dtos/account/AccountPatchDto.java, src/main/java/dev/realtards/kuenyawz/dtos/account/AccountPutDto.java, src/main/java/dev/realtards/kuenyawz/dtos/account/AccountRegistrationDto.java, src/main/java/dev/realtards/kuenyawz/dtos/account/PrivilegeUpdateDto.java, src/main/java/dev/realtards/kuenyawz/dtos/product/ProductPatchDto.java, src/main/java/dev/realtards/kuenyawz/dtos/product/ProductPostDto.java, src/main/java/dev/realtards/kuenyawz/dtos/product/VariantPatchDto.java, src/main/java/dev/realtards/kuenyawz/dtos/product/VariantPostDto.java, src/main/java/dev/realtards/kuenyawz/exceptions/ResourceExistsException.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java, src/main/java/dev/realtards/kuenyawz/utils/stringtrimmer/CleanString.java, src/main/java/dev/realtards/kuenyawz/utils/stringtrimmer/CleanStringAspect.java, src/test/java/dev/realtards/kuenyawz/services/ProductServiceImplTest.java
Used custom annotation `@CleanString` to preprocess incoming requests for POST and PATCH methods. This annotation is applied to String fields that requires it.
=> Trimming on dto processingpre processing for string fields

src/main/java/dev/realtards/kuenyawz/controllers/ProductController.java, src/main/java/dev/realtards/kuenyawz/dtos/product/ProductCsvPostDto.java, src/main/java/dev/realtards/kuenyawz/services/ProductCsvImportService.java, src/main/java/dev/realtards/kuenyawz/services/ProductCsvImportServiceImpl.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java
Can now read using the specified format:
name | tagline | description | category | minQuantity | maxQuantity | variant1_type | variant1_price | variant2_type | variant2_price | variant3_type | variant3_price
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Marmer Buttercake | Kelembutan klasik penuh rasa | Buttercake marmer lembut... | Cake | 1 | 10 | 22 x 22 (cm) | 100000 |   |   |   |  
Bolu Tape Keju Bulat | Bolu tape lembut... | Cake | 1 | 10 | 20 cm | 70000 |   |   |   |  
Prol Tape | Manis dan gurih tape khas nusantara | Kue tape singkong... | Cake | 1 | 10 | 20 x 10 (cm) | 40000 |   |   |   |  
Macaroni Schotel | Klasik, lembut, dan kaya keju | Hidangan makaroni dengan... | Cake | 1 | 10 | Sedang 20 x 10 (cm) | 75000 | Besar 20 x 20 (cm) | 160000 
The class, by default …
=> Upload products from csv (semicolon demilited)

src/main/java/dev/realtards/kuenyawz/services/ProductCsvImportServiceImpl.java
=> Loop incrementer should've been incremented by one instead of two

src/main/java/dev/realtards/kuenyawz/configurations/OpenAPIConfig.java, src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java, src/main/java/dev/realtards/kuenyawz/controllers/ProductController.java
Allow non-CSRF requests to the API base URL
=> Fix modifying endpoints with basic authentication

src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java, src/main/java/dev/realtards/kuenyawz/controllers/ProductController.java, src/main/java/dev/realtards/kuenyawz/entities/Account.java, src/main/java/dev/realtards/kuenyawz/entities/Product.java, src/main/java/dev/realtards/kuenyawz/repositories/ProductRepository.java, src/main/java/dev/realtards/kuenyawz/services/ProductService.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java, src/test/java/dev/realtards/kuenyawz/controllers/AccountControllerTest.java, src/test/java/dev/realtards/kuenyawz/services/ProductServiceImplTest.java
product entity now uses deleted flag
=> Prepare entities for soft deletion

src/main/java/dev/realtards/kuenyawz/boostrappers/DatabaseBootstrapper.java, src/test/java/dev/realtards/kuenyawz/boostrappers/DatabaseBootstrapperTest.java
=> Fix misuse of any() (i ignore it lol)

src/main/java/dev/realtards/kuenyawz/entities/Product.java, src/main/java/dev/realtards/kuenyawz/entities/Variant.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java
Reverts issue #32 but fixed with using DTOs to respond instead of the actual entity. Circular backreference should not be a problem anymore.
=> Simplify product and variant entity and dtos

pom.xml, src/main/java/dev/realtards/kuenyawz/configurations/DatabaseConfig.java, src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java, src/main/java/dev/realtards/kuenyawz/controllers/ProductController.java, src/main/java/dev/realtards/kuenyawz/dtos/product/ProductDto.java, src/main/java/dev/realtards/kuenyawz/dtos/product/ProductPatchAvailabilityDto.java, src/main/java/dev/realtards/kuenyawz/dtos/product/ProductPatchDto.java, src/main/java/dev/realtards/kuenyawz/dtos/product/ProductPostDto.java, src/main/java/dev/realtards/kuenyawz/entities/Product.java, src/main/java/dev/realtards/kuenyawz/entities/Variant.java, src/main/java/dev/realtards/kuenyawz/mapper/ProductMapper.java, src/main/java/dev/realtards/kuenyawz/repositories/ProductRepository.java, src/main/java/dev/realtards/kuenyawz/repositories/ProductSpecification.java, src/main/java/dev/realtards/kuenyawz/services/ProductService.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java, src/test/java/dev/realtards/kuenyawz/repositories/VariantRepositoryTest.java, src/test/java/dev/realtards/kuenyawz/services/ProductServiceImplTest.java
Only available for accounts with ADMIN roles
=> Patch availability of products

src/main/java/dev/realtards/kuenyawz/configurations/WebConfig.java, src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java
Moved cors configuration source to SecurityConfig.
=> Added cors configuration source for the filter

src/main/java/dev/realtards/kuenyawz/services/ImageStorageServiceImpl.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java, src/main/resources/templates/batch-upload-form.html
Also refactored returned URLS to use newer API URIs
=> Fix endpoint api/products returning null images

src/main/java/dev/realtards/kuenyawz/services/ImageStorageServiceImpl.java, src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java
=> Sort url images based on id

src/main/java/dev/realtards/kuenyawz/advice/CustomExceptionsHandler.java, src/main/java/dev/realtards/kuenyawz/advice/GlobalExceptionsHandler.java, src/main/java/dev/realtards/kuenyawz/advice/JwtExceptionsHandler.java
=> Fix exception handlers not working, added @Order on the handlers

src/main/java/dev/realtards/kuenyawz/entities/CartItem.java
Reverts vianneynara/kuenyawz-api#154
=> Revert "Hotfix/cart item entity datatype"

src/main/java/dev/realtards/kuenyawz/dtos/cartItem/CartItemPostDto.java
resolved #159 
Update Cart Item DTO for POST request
=> Update Cart Item DTO for post request

src/main/java/dev/realtards/kuenyawz/controllers/AuthController.java
This sets the response's `accessToken` and `refreshToken` to null, 
Example of the returned response from `/api/auth/register` and `/api/auth/login`.
```json
{
"accessToken": null,
"refreshToken": null,
"tokenType": "Bearer",
"iat": 1732270111000,
"exp": 1732273711000
}
```
=> Extracted tokens to http only cookies

src/main/java/dev/realtards/kuenyawz/services/entity/OTPServiceImpl.java
now it checks whether phone number exists before sending OTP and when verifying OTP
=> Added verifier to not send OTP to existing phone number for redundancy

src/main/java/dev/kons/kuenyawz/dtos/cartItem/CartItemPostDto.java
=> Allow empty string on CartItemPostDto's note field validation

src/main/java/dev/kons/kuenyawz/entities/OTP.java, src/main/java/dev/kons/kuenyawz/entities/Purchase.java, src/main/java/dev/kons/kuenyawz/entities/PurchaseItem.java, src/main/java/dev/kons/kuenyawz/entities/RefreshToken.java, src/main/java/dev/kons/kuenyawz/entities/Transaction.java
=> Added @Version -ing fields

src/main/java/dev/kons/kuenyawz/services/entity/CartItemServiceImpl.java
=> Add images to cart item's product DTO

src/main/java/dev/kons/kuenyawz/controllers/CartController.java, src/main/java/dev/kons/kuenyawz/dtos/cartItem/CartItemPatchDto.java, src/main/java/dev/kons/kuenyawz/services/entity/CartItemServiceImpl.java
Fixed patch comparators where it uses the wrong condition to check whether the quantity is correct
=> Elaborate on cart items patch flow

src/main/java/dev/kons/kuenyawz/services/logic/ProductCsvServiceImpl.java
=> Sets the seeded products' availability to true by default

src/main/java/dev/kons/kuenyawz/dtos/auth/OtpVerifyDto.java
=> Fix regex pattern on OtpVerifyDto

src/main/java/dev/kons/kuenyawz/entities/Apriori.java
resolved #212 
Please check first
=> Added Apriori Entity for storing the Rule

src/main/java/dev/kons/kuenyawz/services/entity/TransactionServiceImpl.java
=> Update purchase status on transaction fetching

src/main/java/dev/kons/kuenyawz/controllers/OrderingController.java, src/main/java/dev/kons/kuenyawz/controllers/TransactionController.java, src/main/java/dev/kons/kuenyawz/repositories/PurchaseSpec.java, src/main/java/dev/kons/kuenyawz/repositories/TransactionSpec.java, src/main/java/dev/kons/kuenyawz/services/entity/PurchaseService.java, src/main/java/dev/kons/kuenyawz/services/entity/PurchaseServiceImpl.java, src/main/java/dev/kons/kuenyawz/services/entity/TransactionService.java, src/main/java/dev/kons/kuenyawz/services/entity/TransactionServiceImpl.java
Also added this statuses filter feature in Transactions
=> Split status parameter in get orders

src/main/java/dev/kons/kuenyawz/repositories/PurchaseSpec.java
=> Fix Payment Type not being parsed properly

src/main/java/dev/kons/kuenyawz/configurations/security/SecurityConfig.java, src/main/resources/application.properties
=> Configure actuator's shutdown with ADMIN permission

src/main/java/dev/kons/kuenyawz/services/logic/AprioriService.java, src/main/java/dev/kons/kuenyawz/services/logic/AprioriServiceImpl.java, src/main/java/dev/kons/kuenyawz/services/logic/RecommenderServiceImpl.java
=> Refactor apriori work flow

compose.yaml
Allows build of local project as an image.
=> Fixed docker compose file

src/main/java/dev/kons/kuenyawz/repositories/ProductRepository.java, src/main/java/dev/kons/kuenyawz/services/logic/RecommenderServiceImpl.java
=> update the apriori fix bug

src/main/java/dev/kons/kuenyawz/repositories/ProductRepository.java, src/main/java/dev/kons/kuenyawz/services/logic/RecommenderServiceImpl.java
=> wrong if flow

src/main/java/dev/kons/kuenyawz/services/logic/ImageStorageServiceImpl.java
=> refactor(ImageStorageServiceImpl): no need to print all the posix trace

src/main/java/dev/kons/kuenyawz/services/logic/OrderingServiceImpl.java
Ensure use of CacheEvict instead of CachePut
Took 8 minutes
=> fix(OrderingServiceImpl): caching on ordering logics
